# -----------------------------------------------------------------------------
# Font Configuration
# -----------------------------------------------------------------------------
font_family      JetBrainsMono NF
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12
background_opacity 1

# Window Decoration & Layout
# -----------------------------------------------------------------------------
hide_window_decorations yes
# -----------------------------------------------------------------------------

# Monokai Color Scheme for Kitty

# Special colors
cursor           #F8F8F0
cursor_text_color #272822
selection_foreground #272822
selection_background #F8F8F2

# The 16 terminal colors

# Black
color0           #272822
color8           #75715E

# Red
color1           #F92672
color9           #F92672

# Green
color2           #A6E22E
color10          #A6E22E

# Yello
color3           #E6DB74
color11          #E6DB74

# Blue
color4           #66D9EF
color12          #66D9EF

# Magenta
color5           #AE81FF
color13          #AE81FF

# Cyan
color6           #A1EFE4
color14          #A1EFE4

# White
color7           #F8F8F2
color15          #F8F8F2

# -----------------------------------------------------------------------------
# Miscellaneous Settings
# -----------------------------------------------------------------------------
scrollback_lines 10000
detect_urls      yes
enable_audio_bell no

# Enable smooth cursor trail animation
cursor_trail             1
cursor_trail_decay       0.05 0.2
cursor_trail_start_threshold 0

# Force block cursor for a prominent trail effect
cursor_shape             block

# Remap Ctrl+Backspace to send the Ctrl+W hex code (\x17)
map ctrl+backspace send_text all \x17

map ctrl+t send_text all tmux\r
